

Starting script at Sun Feb  4 01:22:44 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 72, in <module>
    update_and_reset_todo_entries(item)
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 43, in update_and_reset_todo_entries
    'number': page_obj['properties']['[Updated Total Mins Spent]']['formula']['number']
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'number'
Script completed at Sun Feb  4 01:22:46 PST 2024

Starting script at Sun Feb  4 01:43:16 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 71, in <module>
    update_and_reset_todo_entries(item)
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 43, in update_and_reset_todo_entries
    'number': page_obj['properties']['[Updated Total Mins Spent]']['formula']['number']
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'number'
Script completed at Sun Feb  4 01:43:17 PST 2024

Starting script at Sun Feb  4 01:54:38 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 71, in <module>
    update_and_reset_todo_entries(item)
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 43, in update_and_reset_todo_entries
    'number': page_obj['properties']['[Updated Total Mins Spent]']['formula']['number']
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'number'
Script completed at Sun Feb  4 01:54:39 PST 2024

Starting script at Mon Feb  5 00:01:44 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Feb  5 00:01:44 PST 2024

Starting script at Tue Feb  6 00:02:43 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Feb  6 00:02:47 PST 2024

Starting script at Tue Feb  6 19:38:42 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Feb  6 19:38:53 PST 2024

Starting script at Wed Feb  7 00:01:34 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Feb  7 00:01:35 PST 2024

Starting script at Thu Feb  8 00:02:09 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Feb  8 00:02:10 PST 2024

Starting script at Thu Feb  8 15:17:24 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Feb  8 15:17:30 PST 2024
Starting script at Fri Feb  9 13:24:15 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Feb  9 13:24:25 PST 2024

Starting script at Sat Feb 10 00:16:05 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Feb 10 00:16:05 PST 2024

Starting script at Sun Feb 11 00:01:05 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Feb 11 00:01:06 PST 2024

Starting script at Mon Feb 12 00:14:36 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Feb 12 00:14:37 PST 2024

Starting script at Tue Feb 13 00:12:32 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Feb 13 00:12:36 PST 2024

Starting script at Wed Feb 14 00:01:05 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Feb 14 00:01:07 PST 2024

Starting script at Thu Feb 15 00:16:37 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Feb 15 00:16:38 PST 2024

Starting script at Fri Feb 16 00:02:51 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Feb 16 00:02:52 PST 2024

Starting script at Sat Feb 17 00:04:18 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Feb 17 00:04:21 PST 2024

Starting script at Sun Feb 18 00:03:10 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Feb 18 00:03:13 PST 2024

Starting script at Mon Feb 19 00:15:04 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Feb 19 00:15:06 PST 2024

Starting script at Tue Feb 20 00:03:56 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Feb 20 00:03:58 PST 2024

Starting script at Wed Feb 21 00:16:07 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Feb 21 00:16:07 PST 2024

Starting script at Thu Feb 22 00:01:30 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Starting script at Fri Feb 23 00:01:29 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Feb 23 00:01:30 PST 2024

Starting script at Sat Feb 24 00:15:52 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Feb 24 00:15:56 PST 2024

Starting script at Sun Feb 25 00:17:34 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Feb 25 00:17:38 PST 2024

Starting script at Mon Feb 26 00:04:11 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Feb 26 00:04:12 PST 2024

Starting script at Tue Feb 27 00:12:34 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Feb 27 00:12:36 PST 2024

Starting script at Wed Feb 28 00:05:22 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Feb 28 00:05:24 PST 2024

Starting script at Thu Feb 29 00:04:18 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Feb 29 00:04:19 PST 2024

Starting script at Fri Mar  1 00:09:33 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Mar  1 00:09:34 PST 2024

Starting script at Sat Mar  2 00:10:04 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Mar  2 00:10:06 PST 2024

Starting script at Sun Mar  3 00:01:05 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Mar  3 00:01:06 PST 2024

Starting script at Mon Mar  4 00:15:42 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Mar  4 00:15:43 PST 2024

Starting script at Tue Mar  5 00:01:05 PST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Mar  5 00:01:06 PST 2024

Starting script at Wed Mar  6 00:01:04 PST 2024
Script completed at Wed Mar  6 00:01:05 PST 2024

Starting script at Thu Mar  7 00:15:37 PST 2024
Script completed at Thu Mar  7 00:15:40 PST 2024

Starting script at Fri Mar  8 00:01:04 PST 2024
Script completed at Fri Mar  8 00:01:04 PST 2024

Starting script at Sat Mar  9 00:13:21 PST 2024
Script completed at Sat Mar  9 00:13:22 PST 2024

Starting script at Sun Mar 10 00:15:11 PST 2024
Script completed at Sun Mar 10 00:15:11 PST 2024

Starting script at Mon Mar 11 00:08:16 PDT 2024
Script completed at Mon Mar 11 00:08:17 PDT 2024

Starting script at Mon Mar 11 16:04:01 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Mar 11 16:04:09 PDT 2024

Starting script at Tue Mar 12 00:01:04 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Mar 12 00:01:05 PDT 2024

Starting script at Tue Mar 12 15:53:15 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Mar 12 15:53:29 PDT 2024

Starting script at Wed Mar 13 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Mar 13 00:01:06 PDT 2024

Starting script at Thu Mar 14 00:09:07 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Mar 14 00:09:10 PDT 2024

Starting script at Thu Mar 14 15:13:43 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Mar 14 15:13:54 PDT 2024

Starting script at Fri Mar 15 00:06:11 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Mar 15 00:06:12 PDT 2024

Starting script at Sat Mar 16 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Mar 16 00:01:06 PDT 2024

Starting script at Sun Mar 17 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Mar 17 00:01:06 PDT 2024

Starting script at Mon Mar 18 00:09:06 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Mar 18 00:09:07 PDT 2024

Starting script at Tue Mar 19 00:10:27 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Mar 19 00:10:28 PDT 2024

Starting script at Wed Mar 20 00:13:45 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/ssl.py", line 1296, in recv
    return self.read(buflen)
           ^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/ssl.py", line 1169, in read
    return self._sslobj.read(len)
           ^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 133, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 111, in handle_request
    ) = self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 176, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 212, in _receive_event
    data = self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 191, in request
    response = self.client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 16, in <module>
    db = notion.databases.query(**{'database_id': TODO_DATABASE_ID}).get('results')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/api_endpoints.py", line 132, in query
    return self.parent.request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 193, in request
    raise RequestTimeoutError()
notion_client.errors.RequestTimeoutError: Request to Notion API has timed out
Script completed at Wed Mar 20 02:14:55 PDT 2024

Starting script at Thu Mar 21 00:13:56 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Mar 21 00:13:57 PDT 2024

Starting script at Fri Mar 22 00:14:57 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Mar 22 00:14:58 PDT 2024

Starting script at Sat Mar 23 00:10:31 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Mar 23 00:10:33 PDT 2024

Starting script at Sun Mar 24 00:13:55 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Mar 24 00:13:57 PDT 2024

Starting script at Mon Mar 25 00:04:39 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Mar 25 00:04:41 PDT 2024

Starting script at Tue Mar 26 00:08:06 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Mar 26 00:08:08 PDT 2024

Starting script at Tue Mar 26 18:19:01 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Mar 26 18:19:11 PDT 2024

Starting script at Wed Mar 27 00:01:32 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Mar 27 00:01:34 PDT 2024

Starting script at Thu Mar 28 00:13:26 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Mar 28 00:13:27 PDT 2024

Starting script at Fri Mar 29 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Mar 29 00:01:06 PDT 2024

Starting script at Sat Mar 30 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Mar 30 00:01:06 PDT 2024

Starting script at Sun Mar 31 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Mar 31 00:01:06 PDT 2024

Starting script at Mon Apr  1 00:05:23 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Apr  1 00:05:25 PDT 2024

Starting script at Tue Apr  2 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Apr  2 00:01:06 PDT 2024

Starting script at Wed Apr  3 00:16:09 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Apr  3 00:16:10 PDT 2024

Starting script at Thu Apr  4 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Apr  4 00:01:06 PDT 2024

Starting script at Fri Apr  5 00:09:02 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Apr  5 00:09:04 PDT 2024

Starting script at Sat Apr  6 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Apr  6 00:01:06 PDT 2024

Starting script at Sun Apr  7 00:03:18 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Apr  7 00:03:20 PDT 2024

Starting script at Mon Apr  8 00:03:13 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Apr  8 00:03:19 PDT 2024

Starting script at Tue Apr  9 00:09:14 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Apr  9 00:09:17 PDT 2024

Starting script at Wed Apr 10 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Apr 10 00:01:07 PDT 2024

Starting script at Thu Apr 11 00:11:10 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Apr 11 00:11:11 PDT 2024

Starting script at Fri Apr 12 00:03:12 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Apr 12 00:03:13 PDT 2024

Starting script at Sat Apr 13 00:16:48 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/ssl.py", line 1296, in recv
    return self.read(buflen)
           ^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/ssl.py", line 1169, in read
    return self._sslobj.read(len)
           ^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 133, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 111, in handle_request
    ) = self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 176, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 212, in _receive_event
    data = self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 191, in request
    response = self.client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 16, in <module>
    db = notion.databases.query(**{'database_id': TODO_DATABASE_ID}).get('results')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/api_endpoints.py", line 132, in query
    return self.parent.request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 193, in request
    raise RequestTimeoutError()
notion_client.errors.RequestTimeoutError: Request to Notion API has timed out
Script completed at Sat Apr 13 01:43:10 PDT 2024

Starting script at Sun Apr 14 00:15:36 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Apr 14 00:15:38 PDT 2024

Starting script at Mon Apr 15 00:05:44 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Apr 15 00:05:46 PDT 2024

Starting script at Tue Apr 16 00:14:06 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/ssl.py", line 1296, in recv
    return self.read(buflen)
           ^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/ssl.py", line 1169, in read
    return self._sslobj.read(len)
           ^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 133, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 111, in handle_request
    ) = self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 176, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 212, in _receive_event
    data = self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 191, in request
    response = self.client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 16, in <module>
    db = notion.databases.query(**{'database_id': TODO_DATABASE_ID}).get('results')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/api_endpoints.py", line 132, in query
    return self.parent.request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 193, in request
    raise RequestTimeoutError()
notion_client.errors.RequestTimeoutError: Request to Notion API has timed out
Script completed at Tue Apr 16 02:10:26 PDT 2024

Starting script at Wed Apr 17 00:14:16 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Apr 17 00:14:18 PDT 2024

Starting script at Thu Apr 18 00:15:46 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Apr 18 00:15:48 PDT 2024

Starting script at Sat May 11 10:16:17 CEST 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 16, in <module>
    db = notion.databases.query(**{'database_id': TODO_DATABASE_ID}).get('results')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/api_endpoints.py", line 132, in query
    return self.parent.request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 191, in request
    response = self.client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known
Script completed at Sat May 11 10:16:29 CEST 2024

Starting script at Sat May 11 15:03:35 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 16, in <module>
    db = notion.databases.query(**{'database_id': TODO_DATABASE_ID}).get('results')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/api_endpoints.py", line 132, in query
    return self.parent.request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 191, in request
    response = self.client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known
Script completed at Sat May 11 15:03:35 PDT 2024

Starting script at Sun May 12 15:07:24 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/ssl.py", line 1296, in recv
    return self.read(buflen)
           ^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/ssl.py", line 1169, in read
    return self._sslobj.read(len)
           ^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 133, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 111, in handle_request
    ) = self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 176, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 212, in _receive_event
    data = self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 191, in request
    response = self.client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 16, in <module>
    db = notion.databases.query(**{'database_id': TODO_DATABASE_ID}).get('results')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/api_endpoints.py", line 132, in query
    return self.parent.request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 193, in request
    raise RequestTimeoutError()
notion_client.errors.RequestTimeoutError: Request to Notion API has timed out
Script completed at Sun May 12 17:01:38 PDT 2024

Starting script at Mon May 13 15:09:00 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon May 13 15:09:03 PDT 2024

Starting script at Tue May 14 15:05:59 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue May 14 15:06:01 PDT 2024

Starting script at Tue May 14 18:41:23 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue May 14 18:41:34 PDT 2024
Starting script at Wed May 15 00:13:06 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed May 15 00:13:08 PDT 2024

Starting script at Thu May 16 00:02:54 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu May 16 00:02:56 PDT 2024

Starting script at Fri May 17 00:01:40 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri May 17 00:01:42 PDT 2024

Starting script at Sat May 18 01:04:44 MDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 16, in <module>
    db = notion.databases.query(**{'database_id': TODO_DATABASE_ID}).get('results')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/api_endpoints.py", line 132, in query
    return self.parent.request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 191, in request
    response = self.client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known
Script completed at Sat May 18 01:04:44 MDT 2024

Starting script at Sun May 19 01:03:12 MDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 16, in <module>
    db = notion.databases.query(**{'database_id': TODO_DATABASE_ID}).get('results')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/api_endpoints.py", line 132, in query
    return self.parent.request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 191, in request
    response = self.client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known
Script completed at Sun May 19 01:03:12 MDT 2024

Starting script at Mon May 20 01:13:16 MDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon May 20 01:13:18 MDT 2024

Starting script at Tue May 21 01:12:42 MDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue May 21 01:12:43 MDT 2024

Starting script at Wed May 22 01:09:45 MDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed May 22 01:09:49 MDT 2024

Starting script at Thu May 23 01:07:06 MDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu May 23 01:07:08 MDT 2024

Starting script at Fri May 24 01:01:12 MDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri May 24 01:01:14 MDT 2024

Starting script at Sat May 25 01:05:12 MDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 16, in <module>
    db = notion.databases.query(**{'database_id': TODO_DATABASE_ID}).get('results')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/api_endpoints.py", line 132, in query
    return self.parent.request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 191, in request
    response = self.client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known
Script completed at Sat May 25 01:05:12 MDT 2024

Starting script at Sun May 26 01:08:12 MDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 16, in <module>
    db = notion.databases.query(**{'database_id': TODO_DATABASE_ID}).get('results')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/api_endpoints.py", line 132, in query
    return self.parent.request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 191, in request
    response = self.client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known
Script completed at Sun May 26 01:08:12 MDT 2024

Starting script at Mon May 27 01:07:16 MDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 16, in <module>
    db = notion.databases.query(**{'database_id': TODO_DATABASE_ID}).get('results')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/api_endpoints.py", line 132, in query
    return self.parent.request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 191, in request
    response = self.client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known
Script completed at Mon May 27 01:07:16 MDT 2024

Starting script at Tue May 28 00:01:06 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue May 28 00:01:12 PDT 2024

Starting script at Wed May 29 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed May 29 00:01:08 PDT 2024

Starting script at Thu May 30 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu May 30 00:01:07 PDT 2024

Starting script at Fri May 31 00:01:00 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri May 31 00:01:03 PDT 2024

Starting script at Sat Jun  1 00:06:45 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Jun  1 00:06:47 PDT 2024

Starting script at Sun Jun  2 00:01:02 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Jun  2 00:01:04 PDT 2024

Starting script at Mon Jun  3 00:02:03 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Jun  3 00:02:05 PDT 2024

Starting script at Tue Jun  4 00:01:34 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Jun  4 00:01:36 PDT 2024

Starting script at Wed Jun  5 00:01:01 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Jun  5 00:01:14 PDT 2024

Starting script at Thu Jun  6 00:01:06 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Jun  6 00:01:26 PDT 2024

Starting script at Fri Jun  7 00:16:45 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Jun  7 00:16:47 PDT 2024

Starting script at Sat Jun  8 00:11:55 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Jun  8 00:11:57 PDT 2024

Starting script at Sun Jun  9 00:03:13 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Jun  9 00:03:15 PDT 2024

Starting script at Mon Jun 10 00:01:13 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Jun 10 00:01:16 PDT 2024

Starting script at Tue Jun 11 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Jun 11 00:01:07 PDT 2024

Starting script at Wed Jun 12 00:02:32 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Jun 12 00:02:34 PDT 2024

Starting script at Thu Jun 13 00:02:34 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Jun 13 00:02:36 PDT 2024

Starting script at Fri Jun 14 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Jun 14 00:01:08 PDT 2024

Starting script at Sat Jun 15 00:04:28 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Jun 15 00:04:31 PDT 2024

Starting script at Sun Jun 16 00:01:04 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Jun 16 00:01:06 PDT 2024

Starting script at Mon Jun 17 00:01:36 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Jun 17 00:01:39 PDT 2024

Starting script at Tue Jun 18 00:04:23 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Jun 18 00:04:26 PDT 2024

Starting script at Wed Jun 19 00:03:59 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Jun 19 00:04:02 PDT 2024

Starting script at Thu Jun 20 00:02:12 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Jun 20 00:02:14 PDT 2024

Starting script at Fri Jun 21 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Jun 21 00:01:07 PDT 2024

Starting script at Sat Jun 22 00:01:27 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Jun 22 00:01:29 PDT 2024

Starting script at Sun Jun 23 00:01:02 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Jun 23 00:01:04 PDT 2024

Starting script at Mon Jun 24 00:01:20 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Jun 24 00:01:24 PDT 2024

Starting script at Tue Jun 25 00:01:48 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Jun 25 00:01:52 PDT 2024

Starting script at Wed Jun 26 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Jun 26 00:01:09 PDT 2024

Starting script at Thu Jun 27 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Jun 27 00:01:07 PDT 2024

Starting script at Fri Jun 28 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Jun 28 00:01:07 PDT 2024

Starting script at Sat Jun 29 00:01:00 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Jun 29 00:01:03 PDT 2024

Starting script at Sun Jun 30 00:01:04 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Jun 30 00:01:06 PDT 2024

Starting script at Mon Jul  1 00:03:34 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Jul  1 00:03:38 PDT 2024

Starting script at Tue Jul  2 00:01:03 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Jul  2 00:01:09 PDT 2024

Starting script at Wed Jul  3 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Jul  3 00:01:07 PDT 2024

Starting script at Thu Jul  4 00:01:26 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Jul  4 00:01:30 PDT 2024

Starting script at Fri Jul  5 00:08:33 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 16, in <module>
    db = notion.databases.query(**{'database_id': TODO_DATABASE_ID}).get('results')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/api_endpoints.py", line 132, in query
    return self.parent.request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 191, in request
    response = self.client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known
Script completed at Fri Jul  5 00:08:33 PDT 2024

Starting script at Sat Jul  6 00:10:30 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 16, in <module>
    db = notion.databases.query(**{'database_id': TODO_DATABASE_ID}).get('results')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/api_endpoints.py", line 132, in query
    return self.parent.request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 191, in request
    response = self.client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known
Script completed at Sat Jul  6 00:10:30 PDT 2024

Starting script at Sun Jul  7 00:01:32 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Jul  7 00:01:36 PDT 2024

Starting script at Mon Jul  8 00:01:45 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Jul  8 00:07:48 PDT 2024

Starting script at Tue Jul  9 00:05:06 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Jul  9 00:05:12 PDT 2024

Starting script at Wed Jul 10 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Jul 10 00:01:07 PDT 2024

Starting script at Thu Jul 11 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Jul 11 00:01:08 PDT 2024

Starting script at Fri Jul 12 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Jul 12 00:01:07 PDT 2024

Starting script at Sat Jul 13 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Jul 13 00:01:07 PDT 2024

Starting script at Sun Jul 14 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Jul 14 00:01:07 PDT 2024

Starting script at Mon Jul 15 00:01:03 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Jul 15 00:01:05 PDT 2024

Starting script at Tue Jul 16 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Jul 16 00:01:10 PDT 2024

Starting script at Wed Jul 17 00:05:28 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Jul 17 00:05:31 PDT 2024

Starting script at Thu Jul 18 00:01:04 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Jul 18 00:01:07 PDT 2024

Starting script at Fri Jul 19 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Jul 19 00:01:07 PDT 2024

Starting script at Sat Jul 20 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Jul 20 00:01:09 PDT 2024

Starting script at Sun Jul 21 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Jul 21 00:01:08 PDT 2024

Starting script at Mon Jul 22 00:01:44 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Jul 22 00:01:46 PDT 2024

Starting script at Tue Jul 23 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Jul 23 00:01:07 PDT 2024

Starting script at Wed Jul 24 00:02:58 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Jul 24 00:02:59 PDT 2024

Starting script at Thu Jul 25 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Jul 25 00:01:12 PDT 2024

Starting script at Fri Jul 26 00:01:03 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Jul 26 00:01:05 PDT 2024

Starting script at Sat Jul 27 00:01:04 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Jul 27 00:01:05 PDT 2024

Starting script at Sun Jul 28 00:01:04 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Jul 28 00:01:07 PDT 2024

Starting script at Mon Jul 29 00:01:04 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Jul 29 00:01:08 PDT 2024

Starting script at Tue Jul 30 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Jul 30 00:01:08 PDT 2024

Starting script at Tue Jul 30 15:54:19 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Jul 30 15:54:35 PDT 2024

Starting script at Wed Jul 31 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Jul 31 00:01:09 PDT 2024

Starting script at Thu Aug  1 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Aug  1 00:01:08 PDT 2024

Starting script at Fri Aug  2 00:01:02 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Aug  2 00:01:06 PDT 2024

Starting script at Sat Aug  3 00:02:04 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Aug  3 00:02:06 PDT 2024

Starting script at Sun Aug  4 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Aug  4 00:01:07 PDT 2024

Starting script at Mon Aug  5 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Aug  5 00:01:09 PDT 2024

Starting script at Tue Aug  6 00:01:00 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Aug  6 00:01:31 PDT 2024

Starting script at Wed Aug  7 00:01:03 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Aug  7 00:01:07 PDT 2024

Starting script at Thu Aug  8 00:01:04 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Aug  8 00:01:13 PDT 2024

Starting script at Fri Aug  9 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Aug  9 00:01:12 PDT 2024

Starting script at Sat Aug 10 00:01:26 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Aug 10 00:01:28 PDT 2024

Starting script at Sun Aug 11 00:01:04 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Aug 11 00:01:05 PDT 2024

Starting script at Mon Aug 12 00:01:04 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Aug 12 00:01:06 PDT 2024

Starting script at Tue Aug 13 00:12:10 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Aug 13 00:12:14 PDT 2024

Starting script at Wed Aug 14 00:01:49 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Aug 14 00:01:52 PDT 2024

Starting script at Thu Aug 15 00:03:34 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Aug 15 00:03:36 PDT 2024

Starting script at Fri Aug 16 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Aug 16 00:01:09 PDT 2024

Starting script at Sat Aug 17 00:05:35 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Aug 17 00:05:38 PDT 2024

Starting script at Sun Aug 18 00:16:14 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Aug 18 00:16:16 PDT 2024

Starting script at Sun Aug 18 11:15:24 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Aug 18 11:15:34 PDT 2024

Starting script at Mon Aug 19 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Aug 19 00:01:09 PDT 2024

Starting script at Tue Aug 20 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Aug 20 00:01:10 PDT 2024

Starting script at Wed Aug 21 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Aug 21 00:01:08 PDT 2024

Starting script at Thu Aug 22 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Aug 22 00:01:07 PDT 2024

Starting script at Fri Aug 23 00:01:00 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Aug 23 00:01:02 PDT 2024

Starting script at Sat Aug 24 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Aug 24 00:01:07 PDT 2024

Starting script at Sun Aug 25 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Aug 25 00:01:09 PDT 2024

Starting script at Mon Aug 26 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Aug 26 00:01:15 PDT 2024

Starting script at Tue Aug 27 00:01:59 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Aug 27 00:02:01 PDT 2024

Starting script at Wed Aug 28 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Aug 28 00:01:08 PDT 2024

Starting script at Thu Aug 29 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Aug 29 00:01:11 PDT 2024

Starting script at Fri Aug 30 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Aug 30 00:01:08 PDT 2024

Starting script at Sat Aug 31 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Aug 31 00:01:09 PDT 2024

Starting script at Sun Sep  1 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Sep  1 00:01:07 PDT 2024

Starting script at Mon Sep  2 00:01:02 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Sep  2 00:01:08 PDT 2024

Starting script at Tue Sep  3 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Sep  3 00:01:12 PDT 2024

Starting script at Tue Sep  3 14:52:32 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Sep  3 14:52:54 PDT 2024

Starting script at Wed Sep  4 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Sep  4 00:01:09 PDT 2024

Starting script at Thu Sep  5 00:03:27 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Sep  5 00:03:30 PDT 2024

Starting script at Fri Sep  6 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Sep  6 00:01:06 PDT 2024

Starting script at Sat Sep  7 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Sep  7 00:01:07 PDT 2024

Starting script at Sun Sep  8 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Sep  8 00:01:08 PDT 2024

Starting script at Mon Sep  9 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Sep  9 00:01:09 PDT 2024

Starting script at Tue Sep 10 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Sep 10 00:01:06 PDT 2024

Starting script at Wed Sep 11 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Sep 11 00:01:15 PDT 2024

Starting script at Thu Sep 12 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Sep 12 00:01:07 PDT 2024

Starting script at Fri Sep 13 00:01:01 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Sep 13 00:01:07 PDT 2024

Starting script at Sat Sep 14 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Sep 14 00:01:10 PDT 2024

Starting script at Sun Sep 15 00:01:02 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Sep 15 00:01:04 PDT 2024

Starting script at Mon Sep 16 00:04:42 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Sep 16 00:04:44 PDT 2024

Starting script at Tue Sep 17 00:05:49 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Tue Sep 17 00:05:52 PDT 2024

Starting script at Wed Sep 18 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Sep 18 00:01:07 PDT 2024

Starting script at Thu Sep 19 00:03:09 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Sep 19 00:03:12 PDT 2024

Starting script at Fri Sep 20 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Sep 20 00:01:11 PDT 2024

Starting script at Fri Sep 20 18:10:29 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Sep 20 18:10:48 PDT 2024

Starting script at Sat Sep 21 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sat Sep 21 00:01:12 PDT 2024

Starting script at Sun Sep 22 00:01:02 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Sun Sep 22 00:01:06 PDT 2024

Starting script at Mon Sep 23 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Mon Sep 23 00:01:10 PDT 2024

Starting script at Tue Sep 24 00:04:23 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/ssl.py", line 1296, in recv
    return self.read(buflen)
           ^^^^^^^^^^^^^^^^^
  File "/Users/andrew/anaconda3/lib/python3.11/ssl.py", line 1169, in read
    return self._sslobj.read(len)
           ^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 133, in handle_request
    raise exc
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 111, in handle_request
    ) = self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 176, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 212, in _receive_event
    data = self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 191, in request
    response = self.client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/Users/andrew/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 16, in <module>
    db = notion.databases.query(**{'database_id': TODO_DATABASE_ID}).get('results')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/api_endpoints.py", line 132, in query
    return self.parent.request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/andrew/Scripts/Notion-Integrations/.venv/lib/python3.11/site-packages/notion_client/client.py", line 193, in request
    raise RequestTimeoutError()
notion_client.errors.RequestTimeoutError: Request to Notion API has timed out
Script completed at Tue Sep 24 00:29:40 PDT 2024

Starting script at Wed Sep 25 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Wed Sep 25 00:01:15 PDT 2024

Starting script at Thu Sep 26 00:06:31 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Thu Sep 26 00:06:37 PDT 2024

Starting script at Fri Sep 27 00:01:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
Script completed at Fri Sep 27 00:01:11 PDT 2024

Starting script at Fri Sep 27 15:02:05 PDT 2024
Traceback (most recent call last):
  File "/Users/andrew/Scripts/Notion-Integrations/todo_reset_script.py", line 94, in <module>
    if item['properties']['[Recurring?]']['checkbox'] == True:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '[Recurring?]'
